In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('/mnt/d/迅雷下载/鲍曼组装/merged.csv',low_memory=False)
df

,accession,publication_date,sample_name,strain,collection_date,env_broad_scale,env_local_scale,env_medium,geo_loc_name,lat_lon,...,ID,id,COUNTRYORIGIN,RAISINGCLAIM1,MEATCUT,cultivar,ecotype,age,dev_stage,tissue
0,SAMD00028838,2015-10-13T00:00:00.000,HE-A1,HE-A1,2008,not applicable,not applicable,not applicable,USA,not applicable,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,SAMD00028839,2015-10-13T00:00:00.000,HE-A10,HE-A10,2008,not applicable,not applicable,not applicable,USA,not applicable,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,SAMD00028840,2015-10-13T00:00:00.000,HE-A11,HE-A11,2007,not applicable,not applicable,not applicable,USA,not applicable,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SAMD00028843,2015-10-13T00:00:00.000,HE-A14,HE-A14,2008,not applicable,not applicable,not applicable,USA,not applicable,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,SAMD00028844,2015-10-13T00:00:00.000,HE-A15,HE-A15,2008,not applicable,not applicable,not applicable,USA,not applicable,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10163,SAMN27020382,2022-03-28T00:00:00.000,NaN,not collected,2022-03-08,NaN,NaN,NaN,USA,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10164,SAMN27020385,2022-03-28T00:00:00.000,NaN,not collected,2022-03-15,NaN,NaN,NaN,USA,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10165,SAMN27024972,2022-03-28T00:00:00.000,NaN,2022GN-00134,2022,NaN,NaN,NaN,USA,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10166,SAMN27024974,2022-03-28T00:00:00.000,NaN,2022GN-00138,2022,NaN,NaN,NaN,USA,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10167,SAMN49846794,2025-07-08T00:00:00.000,NaN,NaN,2024-05-14,NaN,NaN,NaN,"Russia: Moscow, city greenhouse",NaN,...,NaN,NaN,NaN,NaN,NaN,Kovano-Wase mandarin,Pot culture under indoor conditions,3.0,Active vegetation,Fresh leafs

In [3]:
# 由于 df["publication_date"] 符合标准ISO格式，可以直接使用方法
df["publication_date"] = pd.to_datetime(df["publication_date"])

In [4]:
# 分拆为 年/月/日/时/分/秒
df["year"] = df["publication_date"].dt.year
df["month"] = df["publication_date"].dt.month
df["day"] = df["publication_date"].dt.day
df["hour"] = df["publication_date"].dt.hour
df["minute"] = df["publication_date"].dt.minute
df["second"] = df["publication_date"].dt.second

In [5]:
df

,accession,publication_date,sample_name,strain,collection_date,env_broad_scale,env_local_scale,env_medium,geo_loc_name,lat_lon,...,cultivar,ecotype,age,dev_stage,tissue,year,month,hour,minute,second
0,SAMD00028838,2015-10-13,HE-A1,HE-A1,2008,not applicable,not applicable,not applicable,USA,not applicable,...,NaN,NaN,NaN,NaN,NaN,2015,10,0,0,0
1,SAMD00028839,2015-10-13,HE-A10,HE-A10,2008,not applicable,not applicable,not applicable,USA,not applicable,...,NaN,NaN,NaN,NaN,NaN,2015,10,0,0,0
2,SAMD00028840,2015-10-13,HE-A11,HE-A11,2007,not applicable,not applicable,not applicable,USA,not applicable,...,NaN,NaN,NaN,NaN,NaN,2015,10,0,0,0
3,SAMD00028843,2015-10-13,HE-A14,HE-A14,2008,not applicable,not applicable,not applicable,USA,not applicable,...,NaN,NaN,NaN,NaN,NaN,2015,10,0,0,0
4,SAMD00028844,2015-10-13,HE-A15,HE-A15,2008,not applicable,not applicable,not applicable,USA,not applicable,...,NaN,NaN,NaN,NaN,NaN,2015,10,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10163,SAMN27020382,2022-03-28,NaN,not collected,2022-03-08,NaN,NaN,NaN,USA,NaN,...,NaN,NaN,NaN,NaN,NaN,2022,3,0,0,0
10164,SAMN27020385,2022-03-28,NaN,not collected,2022-03-15,NaN,NaN,NaN,USA,NaN,...,NaN,NaN,NaN,NaN,NaN,2022,3,0,0,0
10165,SAMN27024972,2022-03-28,NaN,2022GN-00134,2022,NaN,NaN,NaN,USA,NaN,...,NaN,NaN,NaN,NaN,NaN,2022,3,0,0,0
10166,SAMN27024974,2022-03-28,NaN,2022GN-00138,2022,NaN,NaN,NaN,USA,NaN,...,NaN,NaN,NaN,NaN,NaN,2022,3,0,0,0
10167,SAMN49846794,2025-07-08,NaN,NaN,2024-05-14,NaN,NaN,NaN,"Russia: Moscow, city greenhouse",NaN,...,Kovano-Wase mandarin,Pot culture under indoor conditions,3.0,Active vegetation,Fresh leafs,2025,7,0,0,0

In [6]:
# 先对 geo_loc_name 做 split
split_cols = df["geo_loc_name"].str.split(":", n=1, expand=True)
# 生成新列
df["Country"] = split_cols[0].str.strip()
df["Location"] = split_cols[1].str.strip()

In [7]:
df

,accession,publication_date,sample_name,strain,collection_date,env_broad_scale,env_local_scale,env_medium,geo_loc_name,lat_lon,...,age,dev_stage,tissue,year,month,hour,minute,second,Country,Location
0,SAMD00028838,2015-10-13,HE-A1,HE-A1,2008,not applicable,not applicable,not applicable,USA,not applicable,...,NaN,NaN,NaN,2015,10,0,0,0,USA,None
1,SAMD00028839,2015-10-13,HE-A10,HE-A10,2008,not applicable,not applicable,not applicable,USA,not applicable,...,NaN,NaN,NaN,2015,10,0,0,0,USA,None
2,SAMD00028840,2015-10-13,HE-A11,HE-A11,2007,not applicable,not applicable,not applicable,USA,not applicable,...,NaN,NaN,NaN,2015,10,0,0,0,USA,None
3,SAMD00028843,2015-10-13,HE-A14,HE-A14,2008,not applicable,not applicable,not applicable,USA,not applicable,...,NaN,NaN,NaN,2015,10,0,0,0,USA,None
4,SAMD00028844,2015-10-13,HE-A15,HE-A15,2008,not applicable,not applicable,not applicable,USA,not applicable,...,NaN,NaN,NaN,2015,10,0,0,0,USA,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10163,SAMN27020382,2022-03-28,NaN,not collected,2022-03-08,NaN,NaN,NaN,USA,NaN,...,NaN,NaN,NaN,2022,3,0,0,0,USA,None
10164,SAMN27020385,2022-03-28,NaN,not collected,2022-03-15,NaN,NaN,NaN,USA,NaN,...,NaN,NaN,NaN,2022,3,0,0,0,USA,None
10165,SAMN27024972,2022-03-28,NaN,2022GN-00134,2022,NaN,NaN,NaN,USA,NaN,...,NaN,NaN,NaN,2022,3,0,0,0,USA,None
10166,SAMN27024974,2022-03-28,NaN,2022GN-00138,2022,NaN,NaN,NaN,USA,NaN,...,NaN,NaN,NaN,2022,3,0,0,0,USA,None
10167,SAMN49846794,2025-07-08,NaN,NaN,2024-05-14,NaN,NaN,NaN,"Russia: Moscow, city greenhouse",NaN,...,3.0,Active vegetation,Fresh leafs,2025,7,0,0,0,Russia,"Moscow, city greenhouse"

In [8]:
def parse_lat_lon(value):
    if pd.isna(value) or value == "NA":
        return (None, None)
    try:
        parts = value.split()
        lat, lat_dir, lon, lon_dir = parts
        lat, lon = float(lat), float(lon)

        # 根据方向修正正负号
        if lat_dir.upper() == "S":
            lat = -lat
        if lon_dir.upper() == "W":
            lon = -lon
        return (lat, lon)
    except Exception:
        return (None, None)

In [9]:
# 应用函数
df[["Latitude", "Longitude"]] = df["lat_lon"].apply(lambda x: pd.Series(parse_lat_lon(x)))

In [20]:
df[['accession','bioproject','SRA']].to_csv('/mnt/c/Users/Administrator/Desktop/meta.csv',index=False)

In [37]:
df_sample_ERR = pd.read_csv('/mnt/d/迅雷下载/鲍曼组装/xml/run_biosample_log.txt',sep='|',comment="#",header = None)
df_sample_ERR = df_sample_ERR[[1,3]]
df_sample_ERR[1] = df_sample_ERR[1].str.strip()
df_sample_ERR[3] = df_sample_ERR[3].str.strip()
df_sample_ERR.to_csv('/mnt/c/Users/Administrator/Desktop/map.csv',index = False, header = None)